

export const TYPES = {
        ADD_TO_CART : "ADD_TO_CART",
        DELETE_ONE_PRODUCT : "DELETE_ONE_PRODUCT",
        DELETE_ALL_PRODUCTS : "DELETE_ALL_PRODUCTS",
        RESET_CART : "RESET_CART",
        ADD_CUPON : "ADD_CUPON",
        ENLARGE_COMBO : "ENLARGE_COMBO",
}